root: true
env:
  node: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:security/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - airbnb-base
  - airbnb-typescript/base
  - plugin:prettier/recommended
ignorePatterns:
  - dist
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  project:
    - tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
  - security
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: .
rules:
  import/no-extraneous-dependencies: off # bundling dev deps
  security/detect-object-injection: off # ts handles this
