root: true
env:
  node: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:security/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/all
  - airbnb-base
  - airbnb-typescript/base
  - plugin:prettier/recommended
ignorePatterns:
  - dist
  - examples
  - index.test.ts
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  project:
    - tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
  - security
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: .
rules:
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  security/detect-object-injection: off

  '@typescript-eslint/no-type-alias': off
  '@typescript-eslint/prefer-readonly-parameter-types': off
