git:
  commitMessage: 'chore: release v${version}'
github:
  release: true
  releaseName: v${version}
plugins:
  '@release-it/conventional-changelog':
    preset: conventionalcommits
    infile: CHANGELOG.md
    ignoreRecommendedBump: true
